package cs.lexer;

/* The following code was generated by JFlex 1.4.3 on 11/7/13 12:36 PM */

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/7/13 12:36 PM from the specification file
 * <tt>Lexer.flex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 10485760;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\2\2\0\1\1\22\0\1\17\6\0\1\51\1\7"+
    "\1\10\1\47\1\5\1\45\1\16\1\6\1\47\1\3\10\4\1\12"+
    "\2\0\1\50\1\46\1\50\2\0\32\14\4\0\1\15\1\0\1\27"+
    "\1\40\1\26\1\21\1\22\1\25\1\33\1\36\1\20\1\41\1\42"+
    "\1\43\1\34\1\23\1\30\1\31\1\14\1\32\1\11\1\24\1\35"+
    "\1\13\1\37\1\14\1\44\1\14\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\2\3\1\1\2\4\3\5\1\6\1\4"+
    "\22\6\1\5\1\7\1\1\1\5\2\2\1\10\1\11"+
    "\1\0\1\12\2\0\1\13\1\12\1\0\1\6\1\14"+
    "\4\6\2\0\2\6\1\5\26\6\3\0\1\15\1\0"+
    "\6\6\1\0\1\14\6\6\1\5\1\6\1\5\15\6"+
    "\1\0\1\16\1\6\1\14\1\6\1\5\2\6\1\14"+
    "\1\0\27\6\1\0\1\5\26\6\1\14\3\6\1\5"+
    "\12\6\1\5\10\6\1\5\4\6\1\5\15\6\1\5"+
    "\10\6\1\5\5\6\1\5\5\6\1\5\5\6\1\5"+
    "\3\6\1\5\2\6\1\5\1\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[250];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\176\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c"+
    "\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c"+
    "\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec"+
    "\0\176\0\u0516\0\u0540\0\u056a\0\u0594\0\u056a\0\176\0\250"+
    "\0\u05be\0\u05e8\0\u0612\0\176\0\u05e8\0\u063c\0\u0666\0\u0690"+
    "\0\u06ba\0\u06e4\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0"+
    "\0\u0666\0\u080a\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906"+
    "\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56"+
    "\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0540"+
    "\0\u0ba6\0\u0bd0\0\176\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78\0\u0ca2"+
    "\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\u0dc8\0\u0df2"+
    "\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0c24\0\u0ec4\0\u0eee\0\u0f18"+
    "\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e\0\u1068"+
    "\0\u1092\0\u10bc\0\u10e6\0\176\0\u1110\0\u113a\0\u1164\0\u1110"+
    "\0\u118e\0\u11b8\0\u11e2\0\u120c\0\u1236\0\u1260\0\u128a\0\u12b4"+
    "\0\u12de\0\u1308\0\u1332\0\u135c\0\u1386\0\u13b0\0\u13da\0\u1404"+
    "\0\u142e\0\u1458\0\u1482\0\u14ac\0\u14d6\0\u1500\0\u152a\0\u1554"+
    "\0\u157e\0\u15a8\0\u15d2\0\u15fc\0\u1554\0\u1626\0\u1650\0\u167a"+
    "\0\u16a4\0\u16ce\0\u16f8\0\u1722\0\u174c\0\u1776\0\u17a0\0\u17ca"+
    "\0\u17f4\0\u181e\0\u1848\0\u1872\0\u189c\0\u18c6\0\u18f0\0\u191a"+
    "\0\u1944\0\u196e\0\u1998\0\176\0\u19c2\0\u19ec\0\u1a16\0\u191a"+
    "\0\u1a40\0\u1a6a\0\u1a94\0\u1abe\0\u1ae8\0\u1b12\0\u1b3c\0\u1b66"+
    "\0\u1b90\0\u1bba\0\u1bba\0\u1be4\0\u1c0e\0\u1c38\0\u1c62\0\u1c8c"+
    "\0\u1cb6\0\u1ce0\0\u1d0a\0\u1d34\0\u1d5e\0\u1d88\0\u1db2\0\u1ddc"+
    "\0\u1db2\0\u1e06\0\u1e30\0\u1e5a\0\u1e84\0\u1eae\0\u1ed8\0\u1f02"+
    "\0\u1f2c\0\u1f56\0\u1f80\0\u1faa\0\u1fd4\0\u1ffe\0\u1f2c\0\u2028"+
    "\0\u2052\0\u207c\0\u20a6\0\u20d0\0\u20fa\0\u2124\0\u214e\0\u207c"+
    "\0\u2178\0\u21a2\0\u21cc\0\u21f6\0\u2220\0\u21a2\0\u224a\0\u2274"+
    "\0\u229e\0\u22c8\0\u22f2\0\u229e\0\u231c\0\u2346\0\u2370\0\u239a"+
    "\0\u23c4\0\u2370\0\u23ee\0\u2418\0\u2442\0\u2418\0\u246c\0\u2496"+
    "\0\u2496\0\176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[250];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\2\13"+
    "\1\14\1\15\1\16\1\17\1\4\1\11\1\6\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\17\1\36\1\37"+
    "\4\17\3\13\1\40\1\41\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\2\13\1\14\1\15\1\16\1\17"+
    "\1\4\1\11\1\42\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\17\1\36\1\37\4\17\2\13\1\43\1\40"+
    "\1\41\1\44\1\45\1\46\46\44\1\47\54\0\1\6"+
    "\50\0\1\50\1\6\14\0\1\6\40\0\1\51\46\0"+
    "\2\10\1\0\1\51\3\0\1\10\42\0\1\7\1\10"+
    "\1\0\1\52\3\0\1\10\40\0\1\53\1\54\2\55"+
    "\5\0\1\55\4\0\1\56\35\0\2\57\4\0\1\57"+
    "\1\60\4\57\1\0\2\57\1\61\1\57\1\62\3\57"+
    "\1\63\4\57\1\64\7\57\10\0\2\10\1\0\1\51"+
    "\1\65\2\0\1\10\1\66\41\0\2\57\4\0\6\57"+
    "\1\0\7\57\1\67\15\57\10\0\2\57\4\0\6\57"+
    "\1\0\25\57\10\0\2\57\4\0\6\57\1\0\1\57"+
    "\1\70\3\57\1\71\17\57\10\0\2\57\4\0\6\57"+
    "\1\0\1\72\6\57\1\73\15\57\10\0\2\57\4\0"+
    "\6\57\1\0\3\57\1\74\17\57\1\75\1\57\10\0"+
    "\2\57\4\0\6\57\1\0\10\57\1\76\14\57\10\0"+
    "\2\57\4\0\6\57\1\0\10\57\1\71\1\57\1\77"+
    "\12\57\10\0\2\57\4\0\6\57\1\0\7\57\1\100"+
    "\2\57\1\101\12\57\10\0\2\57\4\0\6\57\1\0"+
    "\10\57\1\102\14\57\10\0\2\57\4\0\6\57\1\0"+
    "\1\57\1\103\1\57\1\103\2\57\1\104\6\57\1\105"+
    "\7\57\10\0\2\57\4\0\6\57\1\0\12\57\1\71"+
    "\5\57\1\106\4\57\10\0\2\57\4\0\6\57\1\0"+
    "\1\107\1\57\1\110\7\57\1\111\12\57\10\0\2\57"+
    "\4\0\6\57\1\0\15\57\1\112\7\57\10\0\2\57"+
    "\4\0\6\57\1\0\1\113\24\57\10\0\2\57\4\0"+
    "\6\57\1\0\10\57\1\114\4\57\1\115\7\57\10\0"+
    "\2\57\4\0\6\57\1\0\3\57\1\116\21\57\10\0"+
    "\2\57\4\0\6\57\1\0\10\57\1\117\14\57\10\0"+
    "\2\57\4\0\6\57\1\0\24\57\1\71\53\0\1\13"+
    "\4\0\1\50\1\6\14\0\1\42\27\0\1\120\2\0"+
    "\2\120\1\0\3\120\1\121\43\120\51\44\1\0\2\44"+
    "\1\46\46\44\2\0\1\122\1\123\2\55\5\0\1\55"+
    "\4\0\1\124\35\0\2\55\5\0\1\55\41\0\1\54"+
    "\50\0\1\53\1\54\14\0\1\56\35\0\2\125\4\0"+
    "\6\125\1\0\25\125\10\0\2\125\2\0\1\65\1\0"+
    "\2\125\1\126\3\125\1\0\25\125\10\0\2\125\4\0"+
    "\6\125\1\0\6\125\1\127\16\125\10\0\2\125\4\0"+
    "\6\125\1\0\10\125\1\130\14\125\10\0\2\125\4\0"+
    "\6\125\1\0\15\125\1\131\7\125\10\0\2\125\4\0"+
    "\6\125\1\0\20\125\1\132\4\125\11\0\1\133\5\0"+
    "\1\133\51\0\1\134\42\0\2\125\4\0\6\125\1\0"+
    "\23\125\1\135\1\125\10\0\2\125\4\0\6\125\1\0"+
    "\2\125\1\136\22\125\10\0\2\125\4\0\1\137\1\125"+
    "\1\140\3\125\1\0\25\125\10\0\2\125\4\0\6\125"+
    "\1\0\4\125\1\141\20\125\10\0\2\125\4\0\2\125"+
    "\1\142\3\125\1\0\1\125\1\143\23\125\10\0\2\125"+
    "\4\0\1\144\5\125\1\0\25\125\10\0\2\125\4\0"+
    "\6\125\1\0\4\125\1\145\20\125\10\0\2\125\4\0"+
    "\6\125\1\0\15\125\1\144\7\125\10\0\2\125\4\0"+
    "\6\125\1\0\23\125\1\146\1\125\10\0\2\125\4\0"+
    "\6\125\1\0\10\125\1\147\14\125\10\0\2\125\4\0"+
    "\6\125\1\0\3\125\1\150\10\125\1\151\10\125\10\0"+
    "\2\125\4\0\6\125\1\0\1\125\1\145\23\125\10\0"+
    "\2\125\4\0\6\125\1\0\6\125\1\152\16\125\10\0"+
    "\2\125\4\0\6\125\1\0\4\125\1\153\20\125\10\0"+
    "\2\125\4\0\6\125\1\0\21\125\1\154\3\125\10\0"+
    "\2\125\4\0\6\125\1\0\6\125\1\145\16\125\10\0"+
    "\2\125\4\0\6\125\1\0\12\125\1\155\12\125\10\0"+
    "\2\125\4\0\6\125\1\0\10\125\1\156\14\125\10\0"+
    "\2\125\4\0\6\125\1\0\3\125\1\145\21\125\10\0"+
    "\2\125\4\0\2\125\1\157\3\125\1\0\25\125\10\0"+
    "\2\125\4\0\2\125\1\144\3\125\1\0\25\125\10\0"+
    "\2\125\4\0\6\125\1\0\23\125\1\160\1\125\10\0"+
    "\2\125\4\0\6\125\1\0\4\125\1\161\20\125\10\0"+
    "\2\125\4\0\6\125\1\0\12\125\1\162\12\125\5\0"+
    "\1\120\1\163\1\164\3\120\1\121\10\120\1\121\32\120"+
    "\2\0\1\123\50\0\1\122\1\123\14\0\1\124\35\0"+
    "\2\165\4\0\6\165\1\0\25\165\10\0\2\165\4\0"+
    "\1\165\1\166\4\165\1\0\25\165\10\0\2\165\4\0"+
    "\6\165\1\0\4\165\1\167\20\165\10\0\2\165\4\0"+
    "\6\165\1\0\11\165\1\170\13\165\10\0\2\165\4\0"+
    "\6\165\1\0\12\165\1\171\12\165\10\0\2\165\4\0"+
    "\6\165\1\0\4\165\1\172\20\165\10\0\2\133\3\0"+
    "\1\173\1\0\1\133\46\0\1\174\45\0\2\165\4\0"+
    "\6\165\1\0\15\165\1\175\7\165\10\0\2\165\4\0"+
    "\6\165\1\0\3\165\1\176\21\165\10\0\2\165\4\0"+
    "\6\165\1\0\11\165\1\177\13\165\10\0\2\165\4\0"+
    "\6\165\1\0\1\200\24\165\10\0\2\165\4\0\6\165"+
    "\1\0\2\165\1\201\4\165\1\170\15\165\10\0\2\165"+
    "\4\0\6\165\1\0\1\202\24\165\10\0\2\165\4\0"+
    "\5\165\1\203\1\0\25\165\10\0\2\165\4\0\6\165"+
    "\1\0\2\165\1\170\22\165\10\0\2\165\4\0\1\175"+
    "\5\165\1\0\25\165\10\0\2\165\4\0\6\165\1\0"+
    "\14\165\1\170\10\165\10\0\2\165\4\0\6\165\1\0"+
    "\5\165\1\204\17\165\10\0\2\165\4\0\6\165\1\0"+
    "\11\165\1\205\13\165\10\0\2\165\4\0\6\165\1\0"+
    "\2\165\1\206\22\165\10\0\2\165\4\0\6\165\1\0"+
    "\16\165\1\207\6\165\10\0\2\165\4\0\6\165\1\0"+
    "\2\165\1\210\22\165\10\0\2\165\4\0\6\165\1\0"+
    "\5\165\1\211\17\165\10\0\2\165\4\0\6\165\1\0"+
    "\6\165\1\212\4\165\1\213\11\165\10\0\2\165\4\0"+
    "\6\165\1\0\1\214\24\165\10\0\2\165\4\0\6\165"+
    "\1\0\4\165\1\215\20\165\10\0\2\165\4\0\6\165"+
    "\1\0\1\216\24\165\10\0\2\165\4\0\6\165\1\0"+
    "\22\165\1\217\2\165\5\0\2\120\1\164\3\120\1\121"+
    "\43\120\3\0\2\220\4\0\6\220\1\0\25\220\10\0"+
    "\2\220\2\0\1\174\1\0\6\220\1\0\25\220\10\0"+
    "\2\220\4\0\6\220\1\0\1\221\24\220\10\0\2\220"+
    "\4\0\6\220\1\0\6\220\1\222\16\220\10\0\2\220"+
    "\4\0\6\220\1\0\12\220\1\223\12\220\20\0\1\66"+
    "\42\0\1\224\5\0\1\224\42\0\2\220\4\0\6\220"+
    "\1\0\2\220\1\225\22\220\10\0\2\220\4\0\6\220"+
    "\1\0\4\220\1\226\20\220\10\0\2\220\4\0\6\220"+
    "\1\0\23\220\1\227\1\220\10\0\2\220\4\0\1\230"+
    "\5\220\1\0\1\220\1\231\23\220\10\0\2\220\4\0"+
    "\5\220\1\232\1\0\25\220\10\0\2\220\4\0\6\220"+
    "\1\0\12\220\1\233\12\220\10\0\2\220\4\0\6\220"+
    "\1\0\1\234\24\220\10\0\2\220\4\0\6\220\1\0"+
    "\1\235\24\220\10\0\2\220\4\0\6\220\1\0\15\220"+
    "\1\236\7\220\10\0\2\220\4\0\6\220\1\0\11\220"+
    "\1\237\13\220\10\0\2\220\4\0\6\220\1\0\10\220"+
    "\1\240\14\220\10\0\2\220\4\0\6\220\1\0\6\220"+
    "\1\241\16\220\10\0\2\220\4\0\6\220\1\0\10\220"+
    "\1\242\14\220\10\0\2\220\4\0\6\220\1\0\2\220"+
    "\1\243\22\220\10\0\2\220\4\0\6\220\1\0\12\220"+
    "\1\244\12\220\10\0\2\220\4\0\6\220\1\0\3\220"+
    "\1\245\21\220\10\0\2\220\4\0\6\220\1\0\1\246"+
    "\24\220\10\0\2\220\4\0\6\220\1\0\23\220\1\225"+
    "\1\220\10\0\2\220\4\0\6\220\1\0\1\247\24\220"+
    "\10\0\2\250\4\0\6\250\1\0\25\250\10\0\2\250"+
    "\4\0\6\250\1\0\10\250\1\251\14\250\10\0\2\250"+
    "\4\0\6\250\1\0\2\250\1\252\22\250\10\0\2\250"+
    "\4\0\6\250\1\0\7\250\1\253\15\250\10\0\2\224"+
    "\3\0\1\254\1\0\1\224\42\0\2\250\4\0\6\250"+
    "\1\0\1\255\24\250\10\0\2\250\4\0\6\250\1\0"+
    "\7\250\1\256\15\250\10\0\2\250\4\0\6\250\1\0"+
    "\1\257\24\250\10\0\2\250\4\0\6\250\1\0\2\250"+
    "\1\260\22\250\10\0\2\250\4\0\6\250\1\0\17\250"+
    "\1\261\5\250\10\0\2\250\4\0\6\250\1\0\10\250"+
    "\1\262\14\250\10\0\2\250\4\0\6\250\1\0\5\250"+
    "\1\260\17\250\10\0\2\250\4\0\6\250\1\0\13\250"+
    "\1\263\11\250\10\0\2\250\4\0\6\250\1\0\4\250"+
    "\1\264\20\250\10\0\2\250\4\0\6\250\1\0\4\250"+
    "\1\260\20\250\10\0\2\250\4\0\6\250\1\0\12\250"+
    "\1\260\12\250\10\0\2\250\4\0\6\250\1\0\4\250"+
    "\1\252\20\250\10\0\2\250\4\0\6\250\1\0\12\250"+
    "\1\265\12\250\10\0\2\250\4\0\6\250\1\0\1\250"+
    "\1\266\23\250\10\0\2\250\4\0\6\250\1\0\7\250"+
    "\1\267\15\250\10\0\2\250\4\0\6\250\1\0\13\250"+
    "\1\260\11\250\10\0\2\250\4\0\6\250\1\0\11\250"+
    "\1\270\13\250\10\0\2\250\4\0\6\250\1\0\3\250"+
    "\1\271\21\250\10\0\2\272\4\0\6\272\1\0\25\272"+
    "\10\0\2\272\4\0\6\272\1\0\3\272\1\273\21\272"+
    "\10\0\2\272\4\0\5\272\1\274\1\0\25\272\10\0"+
    "\2\272\4\0\6\272\1\0\6\272\1\275\16\272\10\0"+
    "\2\272\4\0\6\272\1\0\5\272\1\276\17\272\10\0"+
    "\2\272\4\0\6\272\1\0\24\272\1\273\10\0\2\272"+
    "\4\0\6\272\1\0\10\272\1\277\14\272\10\0\2\272"+
    "\4\0\6\272\1\0\12\272\1\300\12\272\10\0\2\272"+
    "\4\0\6\272\1\0\3\272\1\301\21\272\10\0\2\272"+
    "\4\0\6\272\1\0\15\272\1\302\7\272\10\0\2\272"+
    "\4\0\6\272\1\0\2\272\1\273\22\272\10\0\2\272"+
    "\4\0\6\272\1\0\14\272\1\273\10\272\10\0\2\272"+
    "\4\0\6\272\1\0\15\272\1\303\7\272\10\0\2\272"+
    "\4\0\6\272\1\0\14\272\1\304\10\272\10\0\2\272"+
    "\4\0\6\272\1\0\23\272\1\305\1\272\10\0\2\272"+
    "\4\0\6\272\1\0\13\272\1\306\11\272\10\0\2\307"+
    "\4\0\6\307\1\0\25\307\10\0\2\307\4\0\6\307"+
    "\1\0\6\307\1\310\16\307\10\0\2\307\4\0\6\307"+
    "\1\0\4\307\1\311\20\307\10\0\2\307\4\0\6\307"+
    "\1\0\1\312\24\307\10\0\2\307\4\0\6\307\1\0"+
    "\3\307\1\311\21\307\10\0\2\307\4\0\6\307\1\0"+
    "\1\313\24\307\10\0\2\307\4\0\6\307\1\0\14\307"+
    "\1\314\10\307\10\0\2\307\4\0\6\307\1\0\12\307"+
    "\1\315\12\307\10\0\2\307\4\0\6\307\1\0\12\307"+
    "\1\316\12\307\10\0\2\307\4\0\5\307\1\317\1\0"+
    "\25\307\10\0\2\307\4\0\6\307\1\0\24\307\1\311"+
    "\10\0\2\307\4\0\5\307\1\320\1\0\25\307\10\0"+
    "\2\321\4\0\6\321\1\0\25\321\10\0\2\321\4\0"+
    "\6\321\1\0\10\321\1\322\14\321\10\0\2\321\4\0"+
    "\6\321\1\0\6\321\1\323\16\321\10\0\2\321\4\0"+
    "\6\321\1\0\4\321\1\324\20\321\10\0\2\321\4\0"+
    "\6\321\1\0\2\321\1\325\22\321\10\0\2\321\4\0"+
    "\6\321\1\0\7\321\1\326\15\321\10\0\2\321\4\0"+
    "\6\321\1\0\2\321\1\327\22\321\10\0\2\321\4\0"+
    "\6\321\1\0\1\330\24\321\10\0\2\321\4\0\1\331"+
    "\5\321\1\0\25\321\10\0\2\332\4\0\6\332\1\0"+
    "\25\332\10\0\2\332\4\0\6\332\1\0\14\332\1\333"+
    "\10\332\10\0\2\332\4\0\6\332\1\0\7\332\1\334"+
    "\15\332\10\0\2\332\4\0\6\332\1\0\4\332\1\335"+
    "\20\332\10\0\2\332\4\0\6\332\1\0\3\332\1\336"+
    "\21\332\10\0\2\332\4\0\6\332\1\0\4\332\1\337"+
    "\20\332\10\0\2\332\4\0\6\332\1\0\1\332\1\340"+
    "\23\332\10\0\2\332\4\0\6\332\1\0\4\332\1\341"+
    "\20\332\10\0\2\342\4\0\6\342\1\0\25\342\10\0"+
    "\2\342\4\0\6\342\1\0\11\342\1\343\13\342\10\0"+
    "\2\342\4\0\6\342\1\0\4\342\1\344\20\342\10\0"+
    "\2\342\4\0\6\342\1\0\2\342\1\345\22\342\10\0"+
    "\2\342\4\0\6\342\1\0\4\342\1\346\20\342\10\0"+
    "\2\342\4\0\6\342\1\0\1\347\24\342\10\0\2\342"+
    "\4\0\6\342\1\0\10\342\1\350\14\342\10\0\2\351"+
    "\4\0\6\351\1\0\25\351\10\0\2\351\4\0\6\351"+
    "\1\0\15\351\1\352\7\351\10\0\2\351\4\0\6\351"+
    "\1\0\1\353\24\351\10\0\2\351\4\0\6\351\1\0"+
    "\3\351\1\354\21\351\10\0\2\351\4\0\6\351\1\0"+
    "\10\351\1\355\14\351\10\0\2\351\4\0\6\351\1\0"+
    "\12\351\1\356\12\351\10\0\2\357\4\0\6\357\1\0"+
    "\25\357\10\0\2\357\4\0\6\357\1\0\4\357\1\360"+
    "\20\357\10\0\2\357\4\0\6\357\1\0\10\357\1\361"+
    "\14\357\10\0\2\357\4\0\6\357\1\0\3\357\1\362"+
    "\21\357\10\0\2\357\4\0\6\357\1\0\7\357\1\363"+
    "\15\357\10\0\2\364\4\0\6\364\1\0\25\364\10\0"+
    "\2\364\4\0\6\364\1\0\2\364\1\365\22\364\10\0"+
    "\2\364\4\0\6\364\1\0\3\364\1\366\21\364\10\0"+
    "\2\364\4\0\6\364\1\0\13\364\1\367\11\364\10\0"+
    "\2\370\4\0\6\370\1\0\25\370\10\0\2\370\4\0"+
    "\6\370\1\0\12\370\1\371\12\370\10\0\2\370\4\0"+
    "\6\370\1\0\2\370\1\371\22\370\10\0\2\372\4\0"+
    "\6\372\1\0\25\372\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9408];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\1\1\11\6\1\1\11\25\1\1\11\5\1\1\11"+
    "\1\0\1\1\2\0\1\11\1\1\1\0\6\1\2\0"+
    "\31\1\3\0\1\11\1\0\6\1\1\0\27\1\1\0"+
    "\1\11\7\1\1\0\27\1\1\0\27\1\1\11\115\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[250];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public static enum Division{IDENTIFICATION,ENVIRONMENT,DATA,PROCEDURE};
	
	private StringBuffer str		= null;
	private Division division		= null;
	private Division lastDivision	= null;
	private String lastIdentifier = null;
	private boolean valued			= false;
	
	private final void setDivision(Division division){
		this.division = division;
	}
	public Division getDivision(){
		return this.division;
	}
	private Map<String,Symbol<?>> tableOfSymbols = new HashMap<String,Symbol<?>>();
	public Map<String,Symbol<?>> getTableOfSymbols(){
		return tableOfSymbols;
	}
	private Symbol found(LexicalUnit unit,String rawText,final int lineNumber,final int columnNumber)throws java.io.IOException{
		Symbol<String> symbol = new Symbol(unit);
		symbol.put(Symbol.LINE,new Integer(lineNumber));
		symbol.put(Symbol.COLUMN,new Integer(columnNumber));
		symbol.setValue(rawText);
		
		switch(unit){
			case DIVISION:	setDivision(lastDivision); break;
			case IDENTIFICATION:
			case ENVIRONMENT:
			case DATA:
			case PROCEDURE: lastDivision = Division.valueOf(unit.toString()); break;
			case PROGRAM: setDivision(null); break;
			default: lastDivision = null;
		}
		if(getDivision() != null && getDivision().equals(Division.DATA)){
			if(unit.equals(LexicalUnit.IDENTIFIER)){
				lastIdentifier	= rawText;
				if(tableOfSymbols.containsKey(lastIdentifier)) yywarning("The variable \""+rawText+"\" is already defined");
				else tableOfSymbols.put(lastIdentifier,symbol);
			}else if(unit.equals(LexicalUnit.VALUE)){
				valued = true;
			}else if(valued){
				valued = false;
				if(lastIdentifier == null) yywarning("Try to assign a value to an inexistant identifier");
				else tableOfSymbols.get(lastIdentifier).put(Symbol.CONTENT,rawText);
			}else{
				if(lastIdentifier != null && unit.equals(LexicalUnit.INTEGER) || unit.equals(LexicalUnit.IDENTIFIER)){
					symbol = new Symbol(LexicalUnit.IMAGE);
					symbol.put(Symbol.LINE,new Integer(lineNumber));
					symbol.put(Symbol.COLUMN,new Integer(columnNumber));
					symbol.setValue(rawText);
				}
				if(symbol.unit.equals(LexicalUnit.IMAGE)){
					if(lastIdentifier == null) yywarning("Try to assign an image to an inexistant identifier");
					else tableOfSymbols.get(lastIdentifier).put(Symbol.IMAGE,rawText);
				}
			}
		}else if(symbol.unit.equals(LexicalUnit.IMAGE)){ //convert image in bad cases
			if(rawText.charAt(0) == '9'){
				yypushback(rawText.length()-1);
				rawText = rawText.substring(0,1);
			}else	if(rawText.contains("(")){
				yypushback(rawText.length()-rawText.indexOf('('));
				rawText = rawText.substring(0,rawText.indexOf('('));
			}
			
			if(rawText.equals("9")){
				symbol = new Symbol(LexicalUnit.INTEGER);
				symbol.put(Symbol.LINE,new Integer(lineNumber));
				symbol.put(Symbol.COLUMN,new Integer(columnNumber));
				symbol.setValue(rawText);
			}else{
				symbol = new Symbol(LexicalUnit.IDENTIFIER);
				symbol.put(Symbol.LINE,new Integer(lineNumber));
				symbol.put(Symbol.COLUMN,new Integer(columnNumber));
				symbol.setValue(rawText);
			}
		}
		
		if(getDivision() != null && getDivision().equals(Division.PROCEDURE)){
			valued = false;
			if(symbol.unit.equals(LexicalUnit.IDENTIFIER) && lastIdentifier == null){
				lastIdentifier = symbol.getValue();
				if(tableOfSymbols.get(lastIdentifier)!= null){/* yywarning("The variable or label \""+lastIdentifier+"\" is already defined");*/}
				else{
					tableOfSymbols.put(lastIdentifier,symbol);
					valued = true;
				}
			}else if(symbol.unit.equals(LexicalUnit.SECTION)){
				forgotLabel(lastIdentifier);
			}
		}
		
		
		return symbol;
	}
	private void forgotLabel(final String identifier){
		Symbol<String> label = null;
		try{
			label = (Symbol<String>)tableOfSymbols.get(identifier);
			if(label != null && label.containsKey(Symbol.IMAGE))
				label = null;//because it is a variable
		}catch(ClassCastException cce){ cce.printStackTrace(); /* we just ignore remaining information from the table*/}
		if(label != null) tableOfSymbols.put(identifier,null);
	}
	protected void yyerror(String message){
		System.err.println(message);
		System.exit(-1);
	}
	protected void yywarning(String message){
		System.err.println(message);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
  	yyline++;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 112) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { yyerror("Not a lexical unit("+yyline+","+yycolumn+"): \""+yytext()+"\"");
          }
        case 15: break;
        case 10: 
          { System.out.println("#"+yytext()+"#"); found(LexicalUnit.REAL,yytext(),yyline,yycolumn);
          }
        case 16: break;
        case 9: 
          { found(LexicalUnit.STRING,"'"+str.toString()+"'",yyline,yycolumn); yybegin(YYINITIAL);
          }
        case 17: break;
        case 5: 
          { return found(LexicalUnit.convert(yytext()),yytext(),yyline,yycolumn);
          }
        case 18: break;
        case 14: 
          { /* just skip white spaces and comments */
          }
        case 19: break;
        case 2: 
          { str.append(yytext());
          }
        case 20: break;
        case 11: 
          { if(getDivision() != null && getDivision().equals(Division.PROCEDURE) && lastIdentifier != null && valued == false){
									forgotLabel(lastIdentifier);
								}
								lastIdentifier = null;
								return found(LexicalUnit.convert("end-of-instruction"),yytext().replaceAll("\r","\\\\r").replaceAll("\n","\\\\n"),yyline,yycolumn);
          }
        case 21: break;
        case 6: 
          { return found(LexicalUnit.IDENTIFIER,yytext(),yyline,yycolumn);
          }
        case 22: break;
        case 7: 
          { str = new StringBuffer();yybegin(STRING);
          }
        case 23: break;
        case 12: 
          { return found(LexicalUnit.IMAGE,yytext(),yyline,yycolumn);
          }
        case 24: break;
        case 4: 
          { return found(LexicalUnit.INTEGER,yytext(),yyline,yycolumn);
          }
        case 25: break;
        case 8: 
          { yyerror("End of line without ending String");
          }
        case 26: break;
        case 1: 
          { /* just skip white spaces */
          }
        case 27: break;
        case 13: 
          { yypushback(yylength()-yytext().lastIndexOf('.'));
								String str = yytext().trim();
								return found(LexicalUnit.INTEGER,str,yyline,yycolumn);
          }
        case 28: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	return new Symbol(LexicalUnit.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
